name: ASP.NET Core CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Get Git Version
      uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /overrideconfig mode=ContinuousDeployment /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""
    - name: Extract Octopus Tools
      run: |
        mkdir /opt/octo
        cd /opt/octo
        wget -O /opt/octo/octopus.zip https://download.octopusdeploy.com/octopus-tools/6.12.0/OctopusTools.6.12.0.portable.zip
        unzip /opt/octo/octopus.zip
        chmod +x /opt/octo/Octo
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish with dotnet
      run: dotnet publish -o site --configuration Release
    - name: Pack Application
      run: >-
        /opt/octo/Octo pack .
        --outFolder /home/runner/work/RandomQuotes/RandomQuotes
        --basePath /home/runner/work/RandomQuotes/RandomQuotes/RandomQuotes/site
        --id RandomQuotes
        --version $(cat /home/runner/work/RandomQuotes/RandomQuotes/version.txt)
        --format zip
    - name: Create Release
      run: |
        curl \
        -sSL \
        -XPOST
        -H "Authorization: token ${{ secrets.GithubToken }}" \
        --data "{\"tag_name\": \"$(cat /home/runner/work/RandomQuotes/RandomQuotes/version.txt)-dev\", \"target_commitish\": \"master\", \"name\": \"$(cat /home/runner/work/RandomQuotes/RandomQuotes/version.txt)-dev\", \"body\": \"Automated release\", \"draft\": false, \"prerelease\": false}" \
        "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
        curl -XGET "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/$(cat /home/runner/work/RandomQuotes/RandomQuotes/version.txt)-dev" >> /home/runner/work/RandomQuotes/RandomQuotes/release.json
    - name: Upload Release
      run: >
        curl
        -sSL
        -XPOST
        -H "Authorization: token ${{ secrets.GithubToken }}"
        --upload-file "/home/runner/work/RandomQuotes/RandomQuotes/RandomQuotes.$(cat /home/runner/work/RandomQuotes/RandomQuotes/version.txt).zip"
        --header "Content-Type:application/octet-stream"
        "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/$(jq --raw-output '.id' /home/runner/work/RandomQuotes/RandomQuotes/release.json)/assets?name=RandomQuotes.$(cat /home/runner/work/RandomQuotes/RandomQuotes/version.txt).zip"