name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish with dotnet
      run: dotnet publish -o site --configuration Release
    - name: Pack Beanstalk App
      run: >-
        /opt/octo/Octo pack .
        --outFolder /home/runner/work/RandomQuotes/RandomQuotes
        --basePath /home/runner/work/RandomQuotes/RandomQuotes/RandomQuotes/site
        --id RandomQuotes
        --version $(cat /home/runner/work/RandomQuotes/RandomQuotes/version.txt)
        --format zip
    - name: Push to Octopus
      run: >-
        if [[ ! -z "${{ secrets.OctopusUrl }}" && ! -z "${{ secrets.OctopusApiKey }}" ]]; then
        /opt/octo/Octo push
        --server ${{ secrets.OctopusUrl }}
        --apiKey ${{ secrets.OctopusApiKey }}
        --package /home/runner/work/RandomQuotes/RandomQuotes/RandomQuotes.$(cat /home/runner/work/RandomQuotes/RandomQuotes/version.txt).zip
        --overwrite-mode IgnoreIfExists;
        fi